services:
  backend:
    image: ryedae/higher-studies-application-tracker_backend:latest
    build:
      context: ./go-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_URL=${DB_URL}
      - PORT=${PORT}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    image: ryedae/higher-studies-application-tracker_frontend:latest
    build:
      context: ./solid-js-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./solid-js-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: ryedae/higher-studies-application-tracker_db:latest
    build:
      context: ./postgresql-database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
