name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Navigate to dir
        run: |
          git config --global --add safe.directory /home/ubuntu/myapps/higher-studies-application-tracker
          cd /home/ubuntu/myapps/higher-studies-application-tracker
          sudo git fetch
          sudo git pull

      - name: Remove previous container
        run: sudo docker compose -f /home/ubuntu/myapps/higher-studies-application-tracker/docker-compose.yml down

      - name: Run Docker Container
        run: sudo docker compose -f /home/ubuntu/myapps/higher-studies-application-tracker/docker-compose.yml up -d --build
