name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Navigate to dir
        run: |
          cd /home/ubuntu/myapps/higher-studies-application-tracker
          git fetch
          git pull

      - name: Remove previous container
        run: sudo docker compose down

      - name: Run Docker Container
        run: sudo docker compose up --build
